import {
  Crown,
  Gem,
  Heart,
  DollarSign,
  PiggyBank,
  Waves,
  Rat,
  Flame,
} from 'lucide-react'

export const cards = [
  {
    id: 1,
    value: 'Crown',
    icon: Crown,
    color: 'bg-yellow-500',
    matched: false,
    flipped: false,
  },
  {
    id: 2,
    value: 'Gem',
    icon: Gem,
    color: 'bg-cyan-500',
    matched: false,
    flipped: false,
  },
  {
    id: 3,
    value: 'Heart',
    icon: Heart,
    color: 'bg-red-500',
    matched: false,
    flipped: false,
  },
  {
    id: 4,
    value: 'DollarSign',
    icon: DollarSign,
    color: 'bg-green-500',
    matched: false,
    flipped: false,
  },
  {
    id: 5,
    value: 'PiggyBank',
    icon: PiggyBank,
    color: 'bg-pink-500',
    matched: false,
    flipped: false,
  },
  {
    id: 6,
    value: 'Waves',
    icon: Waves,
    color: 'bg-blue-500',
    matched: false,
    flipped: false,
  },
  {
    id: 7,
    value: 'Rat',
    icon: Rat,
    color: 'bg-gray-500',
    matched: false,
    flipped: false,
  },
  {
    id: 8,
    value: 'Flame',
    icon: Flame,
    color: 'bg-orange-500',
    matched: false,
    flipped: false,
  },
  {
    id: 9,
    value: 'Crown',
    icon: Crown,
    color: 'bg-yellow-500',
    matched: false,
    flipped: false,
  },
  {
    id: 10,
    value: 'Gem',
    icon: Gem,
    color: 'bg-cyan-500',
    matched: false,
    flipped: false,
  },
  {
    id: 11,
    value: 'Heart',
    icon: Heart,
    color: 'bg-red-500',
    matched: false,
    flipped: false,
  },
  {
    id: 12,
    value: 'DollarSign',
    icon: DollarSign,
    color: 'bg-green-500',
    matched: false,
    flipped: false,
  },
  {
    id: 13,
    value: 'PiggyBank',
    icon: PiggyBank,
    color: 'bg-pink-500',
    matched: false,
    flipped: false,
  },
  {
    id: 14,
    value: 'Waves',
    icon: Waves,
    color: 'bg-blue-500',
    matched: false,
    flipped: false,
  },
  {
    id: 15,
    value: 'Rat',
    icon: Rat,
    color: 'bg-gray-500',
    matched: false,
    flipped: false,
  },
  {
    id: 16,
    value: 'Flame',
    icon: Flame,
    color: 'bg-orange-500',
    matched: false,
    flipped: false,
  },
]
